optiqlo/views.py
from turtle import shape
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Glasses, Shape, Material, Order
from datetime import datetime, timedelta
from .forms import CheckoutForm, FriendSend, Help
from . import db
from sqlalchemy import desc

bp = Blueprint('main', __name__)

# Home Page Displaying All Products
@bp.route('/')
def index():
    query = request.args.get('query')
    if query:
        glasses = Glasses.query.filter(Glasses.name.contains(query) | Glasses.description.contains(query)) 
    else:
        glasses = Glasses.query.order_by(Glasses.id).all()
    return render_template('index.html', glasses = glasses, title='cool products') 

@bp.route('/priceascending/')
def ascending():
    glasses = Glasses.query.order_by(Glasses.price).all()
    return render_template('index.html', glasses = glasses, title='cool products') 

@bp.route('/pricedescending/')
def descending():
    glasses = Glasses.query.order_by(desc(Glasses.price)).all()
    return render_template('index.html', glasses = glasses, title='cool products') 

# Display Product Detail
@bp.route('/product/<productname>')
def product(productname):
    glasses = Glasses.query.filter(Glasses.name == productname)
    #material = Material.query.filter(Material.id == materialid)
    #shape = Shape.query.filter(Shape.id == shapeid)
    return render_template('product.html', glasses = glasses)

# Search by Shape Type
@bp.route('/shapes/')
def shapes():
    shapes = Shape.query.order_by(Shape.id).all()
    return render_template('shapes.html', shapes = shapes)

# Search by Shape Category
@bp.route('/shapes/glasses/<int:shapeid>')
def shapesglasses(shapeid):
    glasses = Glasses.query.filter(Glasses.shape_id == shapeid)
    return render_template('productview.html', glasses = glasses, title='interesting shapes')

# Search by Material Type
@bp.route('/materials/')
def materials():
    materials = Material.query.order_by(Material.id).all()
    return render_template('materials.html', materials = materials)

# Search by Material Category
@bp.route('/materials/glasses/<int:materialid>')
def materialsglasses(materialid):
    glasses = Glasses.query.filter(Glasses.material_id == materialid)
    return render_template('productview.html', glasses = glasses, title='exotic materials')

# Search by Male Category
@bp.route('/male/')
def male():
    glasses = Glasses.query.filter(Glasses.gender == 'Male')
    return render_template('productview.html', glasses = glasses, title='male styles')

# Search by Female Category
@bp.route('/female/')
def female():
    glasses = Glasses.query.filter(Glasses.gender == 'Female')
    return render_template('productview.html', glasses = glasses, title='female styles')

# Search by Unisex Category
@bp.route('/unisex/')
def unisex():
    glasses = Glasses.query.filter(Glasses.gender == 'Unisex')
    return render_template('productview.html', glasses = glasses, title='unisex styles')

# Search by Latest Styles Category
@bp.route('/lateststyles/')
def lateststyles():
    glasses = Glasses.query.filter(Glasses.lateststyle == True)
    return render_template('productview.html', glasses = glasses, title='latest styles')

# Contact Us
@bp.route('/contact/')
def contact():
    return render_template('info.html', info = 'Contact Us')

# Pricing
@bp.route('/pricing/')
def pricing():
    return render_template('info.html', info = 'Pricing Information')

# Settings
@bp.route('/settings/')
def settings():
    return render_template('info.html', info = 'Settings')

# Help
@bp.route('/help/')
def help():
    return render_template('info.html', info = 'Help')

# Cart
@bp.route('/orders/', methods=['POST','GET'])
def order():
    glasses_id = request.values.get('glasses_id')

    # Retrieve order if exists
    if 'order_id' in session.keys():
        order = Order.query.get(session['order_id'])
        # Order will be None if order_id stale
    else:
        # There is no order
        order = None

    # Create new order if needed
    if order is None:
        order = Order(status = False, firstname='', surname='', email='', phone='', address_street='', address_city='', address_postcode='', \
            date=datetime.now(), totalcost=0, )
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None
    
    # Calcultate Total Price
    totalprice = 0
    if order is not None:
        for glasses in order.glasses:
            totalprice = totalprice + glasses.price
            
    # Add Item
    if glasses_id is not None and order is not None:
        glasses = Glasses.query.get(glasses_id)
        if glasses not in order.glasses:
            try:
                order.glasses.append(glasses)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your basket'
            return redirect(url_for('main.order'))
        else:
            flash('Item already in basket')
            return redirect(url_for('main.index'))

    itemnumber = len(order.glasses)
    shippingdate = order.date + timedelta(days=3)
    
    return render_template('cart.html', order = order, totalprice = totalprice, itemnumber = itemnumber, shippingdate=shippingdate)

# Delete specific basket items
@bp.route('/deleteorderitem/', methods=['POST'])
def deleteorderitem():
    id=request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        glasses_to_delete = Glasses.query.get(id)
        try:
            order.glasses.remove(glasses_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))

# Scrap basket
@bp.route('/deleteorder/')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))

# Checkout by Entering Details
@bp.route('/checkout/', methods=['POST','GET'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
       
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            order.address_street = form.address_street.data
            order.address_city = form.address_city.data
            order.address_postcode = form.address_postcode.data
            totalcost = 0
            for glasses in order.glasses:
                totalcost = totalcost + glasses.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Thank you for your order!')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'
    return render_template('forms.html', form = form, title='finalise your checkout')

# Send the glasses to a friend
@bp.route('/<productname>/friendsend/', methods=['POST','GET'])
def friendsend(productname):
    form = FriendSend() 
    glasses = Glasses.query.filter(Glasses.name == productname)
       
    if form.validate_on_submit():
        flash('We will send this information to the e-mail!')
        return redirect(url_for('main.index', glasses = glasses))

    return render_template('forms.html', form = form, title='send to someone')

# Make an enquiry
@bp.route('/enquiry/', methods=['POST','GET'])
def enquiry():
    form = Help() 

    if form.validate_on_submit():
        flash('Thank you for your enquiry!')
    return render_template('forms.html', form = form, title='make your enquiry')


optiqlo/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Optiqlo</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<body>
    <!-- putting header inside container will prevent full width navbar -->
    <header>
        <!-- Shopping Cart -->
        <div class="topnav">
            <div class="topnav-right">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                    <a class="glyphicon glyphicon-shopping-cart" aria-hidden="true" style="color:white" href="{{url_for('main.order')}}"><span class="text" href="{{url_for('main.order')}}">Cart</span></a>
                </button>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                    <a class="glyphicon glyphicon-user" aria-hidden="true" style="color:white" href="{{url_for('main.checkout')}}"><span class="text" href="{{url_for('main.checkout')}}">Details</span></a>
                </button>
            </div>
        </div>

        <!-- Hero Image -->
        <section class="hero">
            <div class="hero-content">
                <div class="hero-title">
                    <h1>Welcome to Optiqlo</h1>
                </div>
            </div>
        </section>

        <!-- Nav Bar -->
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for('main.index')}}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"
                            id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            Collections
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{url_for('main.shapes')}}">Shop by
                                Shape</a> 
                            <a class="dropdown-item" href="{{url_for('main.materials')}}">Shop by
                                Materials</a> 
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{url_for('main.lateststyles')}}">Latest Styles</a> 
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Shop
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{url_for('main.male')}}">Male</a>
                            <a class="dropdown-item" href="{{url_for('main.female')}}">Female</a>
                            <a class="dropdown-item"
                                href="{{url_for('main.unisex')}}">Unisex</a> 
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('main.enquiry')}}">Contact Us <span class="sr-only"></span></a>
                    </li>
                </ul>

            </div>
        </nav>
        {% block head %}{% endblock %}
    </header>

    <!-- Main page content goes in container -->
    <div class="container-fluid">
        <main>
            {% block main %}{% endblock %}
        </main>
    </div>

    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center p-4 border-bottom">

            <div>
                <a href="" class="me-4 text-reset">
                    <i></i>
                </a>

                </a>
            </div>

            <!-- Left -->
            <div class="me-5 d-none d-lg-block">
                <span>Let's Keep in Touch</span>
            </div>
            <!-- Left -->

            <!-- Right -->
            <div>
                <a href="" class="me-4 text-reset">
                    <i></i>
                </a>

                </a>
            </div>
            <!-- Right -->
        </section>
        <!-- Section: Social media -->

        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Optiqlo
                        </h6>
                        <p>
                            We are Optiqlo and we sell quality spectacle frames of classic, modern, and timeless
                            designs.
                        </p>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Products
                        </h6>
                        <p>
                            <a href="{{url_for('main.male')}}" class="text-reset">Male</a>
                        </p>
                        <p>
                            <a href="{{url_for('main.female')}}" class="text-reset">Female</a>
                        </p>
                        <p>
                            <a href="{{url_for('main.lateststyles')}}" class="text-reset">Latest Styles</a>
                        </p>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Useful links
                        </h6>
                        <p>
                            <a href="{{url_for('main.pricing')}}" class="text-reset">Pricing</a>
                        </p>
                        <p>
                            <a href="{{url_for('main.settings')}}" class="text-reset">Settings</a>
                        </p>
                        <p>
                            <a href="{{url_for('main.order')}}" class="text-reset">Orders</a>
                        </p>
                        <p>
                            <a href="{{url_for('main.help')}}" class="text-reset">Help</a>
                        </p>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Contact
                        </h6>
                        <p>
                            info@optiqlo.com.au
                        </p>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->

        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2022 Copyright:
            <a class="text-reset fw-bold" href="https://mdbootstrap.com/">Optiqlo.com.au</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

optiqlo/templates/cart.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block main %}

<div class="row co-12 d-flex mt-2 mb-2 justify-content-center">
  <h3>Shopping Cart</h3>
</div>

<section class="h-100 gradient-custom">
  <div class="container py-5">
    <div class="row d-flex justify-content-center my-4">
      <div class="col-md-8">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Cart - {{ itemnumber }} items</h5>
          </div>
          <div class="card-body">
            {% for glasses in order.glasses %}
            <!-- Single item -->
            <div class="row">
              <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                <!-- Image -->
                <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                  <img src="{{url_for('static', filename=('img/' + glasses.image))}}" class="w-100" alt="Frame Image" />
                </div>
                <!-- Image -->
              </div>

              <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                <!-- Data -->
                <p><a
                    href="{{ url_for('main.product', productname=glasses.name) }}"><strong>{{glasses.name}}</strong></a>
                </p>
                <p>Description: {{glasses.description}}</p>
                <p>Size: {{glasses.eyesize}}-{{glasses.bridgesize}}</p>
                <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                  <input type="hidden" id="id" name="id" value="{{glasses.id}}">
                  <input type="submit" value="Delete" class="btn btn-primary btn-sm me-1 mb-2">
                  <i class="glyphicon glyphicon-trash"></i>
                </form>
                <!-- Data -->
              </div>

              <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                <!-- Quantity -->

                <div class="d-flex mb-4" style="max-width: 300px">
                </div>
                <!-- Quantity -->

                <!-- Price -->
                <p class="text-start text-md-center">
                  <strong>{{ "$%.2f"|format(glasses.price) }}</strong>
                </p>
                <!-- Price -->
              </div>
            </div>
            <!-- Single item -->

            <hr class="my-4" />
            {% endfor %}
          </div>
        </div>
        <div class="card mb-4">
          <div class="card-body">
            <p class="mb-0"><strong>Order Date</strong></p>
            <p class="mt-0">{{order.date.strftime("%d-%m-%Y")}}</p>
            <br>
            <p class="mb-0"><strong>Expected Shipping Date</strong></p>
            <p class="mt-0">{{shippingdate.strftime("%d-%m-%Y")}}</p>
            <br>
            <a href="{{ url_for('main.deleteorder') }}" class="btn btn-primary">Empty Basket</a>
          </div>
        </div>

        <div class="card mb-4 mb-lg-0">
          <div class="card-body">
            <p><strong>We accept</strong></p>
            <div class="d-flex mb-4 float-left">
              <img class="mr-4" style="width: 60px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                alt="Visa">
              <img class="mr-4" style="width: 60px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                alt="Mastercard">
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Summary</h5>
          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                Items
                <span>{{ "$%.2f"|format(totalprice) }}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                Shipping
                <span> $10.00 </span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                <div>
                  <strong>Total</strong>
                </div>
                <span><strong>{{ "$%.2f"|format(totalprice+10) }}</strong></span>
              </li>
            </ul>

            <a href="{{url_for('main.checkout')}}"><button type="button" class="btn btn-primary btn-lg btn-block">
              Go to Checkout
            </button></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

optiqlo/templates/index.html
{% extends 'base.html' %}

{% block head %}
<!-- Carousel -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">

    <div class="carousel-item active">
      <section class="carousel-one" alt="First slide"> 
        <div class="carousel-content align-items-bottom">
          <div class="carousel-title">
          </div>
        </div>
      </section>
    </div>

    <div class="carousel-item">
      <section class="carousel-two" alt="Second slide"> 
        <div class="carousel-content">
          <div class="carousel-title"></div>
        </div>
      </section>
    </div>

    <div class="carousel-item">
      <section class="carousel-three" alt="Third slide"> 
        <div class="carousel-content">
          <div class="carousel-title"></div>
        </div>
      </section>
    </div>

  </div>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}

<div class="alert alert-primary" role="alert">
  {% for message in messages %}
  {{ message }}
  {% endfor %}
</div>

{% endif %}
{% endwith %}

{% endblock %}

{% block main %}

<!-- Products -->
<section class="section-products">
  <div class="container">
    <h1 class="hero-content">Check out all of our {{title}}</h1>
    <br>
    <br>
    <div class="d-flex justify-content-center align-items-center">
    <form class="form-inline mx-auto" method="GET">
      Search Name or Description
      <input class="form-control ml-4 mr-sm-2" type="search" placeholder="Search" name="query" style="width: max-width">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
          <span class="glyphicon glyphicon-search" aria-hidden="true" style="color:rgb(0, 0, 0)"></span>
      </button>
    </form>
    <div class="form-inline mx-auto">
      Filter Price
      <div class="d-flex justify-content-center align-items-center"></div>
        <a class="btn btn-outline-success ml-4 my-2 my-sm-0" role="button" href="{{ url_for('main.ascending') }}" type="submit"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true" style="color:rgb(0, 0, 0)"></span></a>
        <a class="btn btn-outline-success ml-2 my-2 my-sm-0" role="button" href="{{ url_for('main.descending') }}" type="submit"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true" style="color:rgb(0, 0, 0)"></span></a>
    </div>
</div>
<br>
    {% for glasses in glasses%}

    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
      <div id="{{glasses.id}}" class="product-content">
        <div class="product-img">
          <a href="{{ url_for('main.product', productname=glasses.name) }}">
            <img src="{{url_for('static', filename='img/'+glasses.image)}}" alt="Card image">
          </a>
        </div>
        <div class="product-btns">
          <form action="{{ url_for('main.order') }}">
            <input type="hidden" id="glasses_id" name="glasses_id" value="{{ glasses.id }}">
            <input class="btn-cart" type="submit" value="Add to Cart">
          </form>
        </div>
        <div id="{{glasses.id}}" class="product-info text-center">
          <p class="product-title">{{glasses.name}}</p>
          <p class="product-price">${{glasses.price}}</p>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
</section>

{% endblock %}

optiqlo/templates/materials.html
{% extends 'base.html' %}

{% block main %}
<!-- display glasses for the specific shape -->
<section>

    <div class="text-dark text-center">
        <div>
            <p class="hero-content">Browse a MATERIAL</p>
        </div>
    </div>
    <section class="section-products">
        <div class="container">
    {% for material in materials%} 
    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
        <div id="{{material.id}}" class="product-content">
          <div class="product-img">
            <a href="{{ url_for('main.materialsglasses', materialid=material.id) }}">
              <img src="{{url_for('static', filename='img/'+material.image)}}" alt="Card image">
            </a>
          </div>
          <div id="{{material.id}}" class="product-info text-center">
            <p class="product-title">{{material.name}}</p>
            <p class="product-price">{{material.description}}</p>
          </div>
        </div>
    </div>
    {% endfor %}
    </div>
    </section>

</section>
{% endblock %}

optiqlo/templates/product.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block main %}

{% for glasses in glasses %}

<!-- Product Detail -->
<div class="container mt-5 mb-5">
  <div class="row d-flex justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="row">
          <div class="col-md-5">
            <div class="images p-2">
              <div class="text-center p-4"> <img id="{{ glasses.id }}" src="{{url_for('static', filename='img/'+glasses.image)}}" width="250" /> </div>
            </div>
          </div>
          <div class="col-md-7">
            <div class="product p-4">
              <div class="d-flex justify-content-end align-items-center">
                <div class="d-flex align-items-center"> <a class="ml-1" href="{{url_for('main.index')}}">Back to Home</a> </div>
              </div>
              <div class="mt-4 mb-3"> <span class="text-uppercase text-muted brand">Optiqlo</span>
                <h5 class="text-uppercase">{{ glasses.name }}</h5>
                <div class="price d-flex flex-row align-items-center"> <span class="price">${{ glasses.price }}</span>
                </div>
              </div>
              <p class="about">{{ glasses.description }}</p>
              <div class="sizes mt-5">
                <h6 class="text-uppercase">Size (eye size - bridge, mm) </h6> <label class="radio"> <input type="radio"
                    name="size" checked> <span>{{ glasses.eyesize }}-{{ glasses.bridgesize }}</span> </label> 
              </div>
              <div class="cart mt-4 align-items-center"> 
                <form action="{{ url_for('main.order') }}">
                  <input type="hidden" id="glasses_id" name="glasses_id" value="{{ glasses.id }}">
                  <input class="btn-cart" type="submit" value="Add to Cart">
                </form>
                 <i class="fa fa-heart text-muted"></i> <i class="fa fa-share-alt text-muted"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<br>
<!-- More Detail -->
<div class="container">
  <h3 class="display-5">More Details</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="col-md-6 col-lg-4 col-xl-4"></th>
        <th class="about col-md-6 col-lg-8 col-xl-8">Specifications</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row" class="about">Name</th>
        <td class="about">{{ glasses.name }}</td>
      </tr>
      <tr>
        <th scope="row mb=0" class="about">Material</th>
        <td class="about">{{ glasses.material_id }} <p>(1 = Acetate; 2 = Metal; 3 = Titanium)</p></td>
      </tr>
      <tr>
        <th scope="row pb=0" class="about">Shape </th>
        <td class="about">{{ glasses.shape_id }} <p>(1 = Rectangular; 2 = Round; 3 = Cats Eye; 4 = Aviator)</p></td>
      </tr>
      <tr>
        <th scope="row" class="about">Gender</th>
        <td class="about">{{ glasses.gender }}</td>
      </tr>
      <tr>
        <th scope="row" class="about">Size (eye size - bridge size)</th>
        <td class="about">{{ glasses.eyesize }}-{{ glasses.bridgesize }}</td>
      </tr>
    </tbody>
  </table>
  <p class="about">This item was hand-made with care by our local technicians.</p>
  <hr class="my-2">
  <br>
  <p class="about">Get another opinion, send it to a friend!</p>
  <p class="lead">
    <a class="btn btn-primary btn-md" href="{{ url_for('main.friendsend', productname=glasses.name) }}" role="button">Send Now</a>
  </p>
</div>
{% endfor %} 
{% endblock %}

optiqlo/templates/results.html
{% extends 'base.html' %}


{% block main %}

<!-- Products -->
<section class="section-products">
  <div class="container">
    <h1 class="hero-content">Check out all of our {{title}}</h1>
    {% for i in range(count)%}

{{result[i]}}

    {% endfor %}
  </div>
</section>

{% endblock %}